"""Part 2, Step 4: run the three assignment prompts through the harness
and write agent/transcript.md (prompt, tool calls, JSON results, answer,
chart references).

Usage:
    python -m agent.run_demo
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from agent import harness
from agent.harness import truncate_for_display

PROMPTS = [
    "Summarize the thermal anomalies today and what likely caused them.",
    "Plot coolant flow and temperature around the incident and highlight warnings.",
    "Draft a service ticket for the most severe issue: root cause, affected "
    "subsystem, recommended action.",
]
TRANSCRIPT_PATH = Path(__file__).with_name("transcript.md")


def _render(result: dict) -> list[str]:
    lines = [f"**Mode:** {result['mode']}"
             + (f" ({result['model']})" if "model" in result else ""), ""]
    for i, call in enumerate(result["tool_calls"], start=1):
        lines += [f"**Tool call {i}:** `{call['tool']}"
                  f"({json.dumps(call['input'], default=str)})`", "",
                  "```json",
                  json.dumps(truncate_for_display(call["result"]),
                             indent=2, default=str, ensure_ascii=False),
                  "```", ""]
        chart = (call["result"].get("chart_path")
                 or call["result"].get("attachment_chart")
                 or call["result"].get("evidence_chart"))
        if chart:
            lines += [f"![chart](../{Path(chart).as_posix()})", ""]
    lines += ["**Answer:**", "", result["answer"], ""]
    return lines


def main() -> None:
    if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
        sys.stdout.reconfigure(encoding="utf-8")
    sections = ["# Agent harness transcript",
                "",
                "Generated by `python -m agent.run_demo` over `outputs/logs.db` "
                "(the three prompts required by the assignment).",
                ""]
    for n, prompt in enumerate(PROMPTS, start=1):
        print(f"[{n}/{len(PROMPTS)}] {prompt}")
        result = harness.answer(prompt)
        print(f"    mode={result['mode']}  tools={[c['tool'] for c in result['tool_calls']]}")
        sections += [f"## Prompt {n}", "", f"> {prompt}", ""] + _render(result)

    TRANSCRIPT_PATH.write_text("\n".join(sections), encoding="utf-8")
    print(f"\nTranscript written to {TRANSCRIPT_PATH}")


if __name__ == "__main__":
    main()
