"""Part 2, Step 4: run the three assignment prompts through the harness
and write agent/transcript.md (prompt, tool calls, JSON results, answer,
chart references).

Usage:
    python -m agent.run_demo
"""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

from agent import harness

PROMPTS = [
    "Summarize the thermal anomalies today and what likely caused them.",
    "Plot coolant flow and temperature around the incident and highlight warnings.",
    "Draft a service ticket for the most severe issue: root cause, affected "
    "subsystem, recommended action.",
]
TRANSCRIPT_PATH = Path(__file__).with_name("transcript.md")
MAX_LIST_ITEMS = 8


def _truncate(value, depth: int = 0):
    """Deep-copy with long lists shortened so the transcript stays readable."""
    if isinstance(value, dict):
        return {k: _truncate(v, depth + 1) for k, v in value.items()}
    if isinstance(value, list) and len(value) > MAX_LIST_ITEMS:
        head = [_truncate(v, depth + 1) for v in value[:MAX_LIST_ITEMS]]
        return head + [f"... ({len(value) - MAX_LIST_ITEMS} more items truncated)"]
    if isinstance(value, list):
        return [_truncate(v, depth + 1) for v in value]
    return value


def _render(result: dict) -> list[str]:
    lines = [f"**Mode:** {result['mode']}"
             + (f" ({result['model']})" if "model" in result else ""), ""]
    for i, call in enumerate(result["tool_calls"], start=1):
        lines += [f"**Tool call {i}:** `{call['tool']}"
                  f"({json.dumps(call['input'], default=str)})`", "",
                  "```json",
                  json.dumps(_truncate(copy.deepcopy(call["result"])),
                             indent=2, default=str, ensure_ascii=False),
                  "```", ""]
        chart = call["result"].get("chart_path")
        if chart:
            lines += [f"![chart](../{Path(chart).as_posix()})", ""]
    lines += ["**Answer:**", "", result["answer"], ""]
    return lines


def main() -> None:
    if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
        sys.stdout.reconfigure(encoding="utf-8")
    sections = ["# Agent harness transcript",
                "",
                "Generated by `python -m agent.run_demo` over `outputs/logs.db` "
                "(the three prompts required by the assignment).",
                ""]
    for n, prompt in enumerate(PROMPTS, start=1):
        print(f"[{n}/{len(PROMPTS)}] {prompt}")
        result = harness.answer(prompt)
        print(f"    mode={result['mode']}  tools={[c['tool'] for c in result['tool_calls']]}")
        sections += [f"## Prompt {n}", "", f"> {prompt}", ""] + _render(result)

    TRANSCRIPT_PATH.write_text("\n".join(sections), encoding="utf-8")
    print(f"\nTranscript written to {TRANSCRIPT_PATH}")


if __name__ == "__main__":
    main()
